vich_uploader:
    db_driver: orm

    mappings:
       member_photos:
           uri_prefix: /images/member_photos
           upload_destination: '%kernel.project_dir%/public/images/member_photos'

           inject_on_load : false 
           delete_on_update : true 
           delete_on_remove : true